#!/usr/bin/env bash

# init <project root directory>

gradlePropertiesFile="$1/gradle.properties"

ReadGradleProperty() {
  local value=`cat $gradlePropertiesFile | grep "$1" | cut -d'=' -f2`
  echo "$value"
}

projectName='mcaselector'
applicationName=$(ReadGradleProperty 'application.name')
applicationURL=$(ReadGradleProperty 'application.url')
applicationAuthor=$(ReadGradleProperty 'application.author')
applicationCopyright=$(ReadGradleProperty 'application.copyright')
applicationVersion=$(ReadGradleProperty 'version')

# Installer <project root> <version>
Installer() {
  mkdir "$1/build/inno"

  $1/installer/init "$1" "$1/build/inno/LICENSE"

  # copy files
  local innoSetupDir="$1/build/inno"
  cp "$1/installer/windows/icon.ico" "$innoSetupDir"
  cp "$1/installer/windows/small.bmp" "$innoSetupDir"
  cp "$1/installer/windows/large.bmp" "$innoSetupDir"
  cp -r "$1/build/jpackage/$applicationName" "$innoSetupDir"
  cp "$1/installer/windows/inno.iss" "$innoSetupDir"
  sed -i "s/\${applicationName}/$applicationName/g" "$innoSetupDir/inno.iss"
  sed -i "s/\${applicationUrl}/${applicationURL////\\/}/g" "$innoSetupDir/inno.iss"
  sed -i "s/\${applicationAuthor}/$applicationAuthor/g" "$innoSetupDir/inno.iss"
  sed -i "s/\${applicationCopyright}/$applicationCopyright/g" "$innoSetupDir/inno.iss"
  sed -i "s/\${applicationVersion}/$applicationVersion/g" "$innoSetupDir/inno.iss"
}

Installer $1

# copy and rename the fat jar
mkdir "$1/build/libs/all"
cp "$1/build/libs/$projectName-$applicationVersion-all.jar" "$1/build/libs/all/$projectName-$applicationVersion.jar"